apiVersion: v1
kind: Secret
metadata:
  name: mirumiru-api-secret
type: Opaque
stringData:
  PROD_DB_URL: "jdbc:postgresql://postgres.example.internal:5432/mirumiru"
  PROD_DB_USERNAME: "mirumiru"
  PROD_DB_PASSWORD: "mirumiru"
  PROD_JWT_SECRET: "replace-with-base64-secret-that-decodes-to-at-least-64-bytes"
  MAIL_USERNAME: "noreply@example.com"
  MAIL_PASSWORD: "replace-me"
