apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: mirumiru-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: git:secret:argocd/git-creds
    gitConfig:
      branch: main
      writeBackTarget: "helmvalues:./values.yaml"
  applicationRefs:
    - namePattern: "mirumiru"
      images:
        - alias: api
          imageName: vantagac/mirumiru-api:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^[0-9a-f]{40}$"
            ignoreTags:
              - latest
            platforms:
              - linux/arm64
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
